Replace inline style by hidden attribute...
Alex-D/Cookies-EU-banner pull request #66
Opened 2022-03-21 15:48 UTC by robsonsobral

...in a retro compatible way

closes #48

2022-03-22 02:13 UTC, robsonsobral commented
Rethinking... My code is retro-compatible only in case the style is set inline. I guess I should change it.

2022-03-22 02:17 UTC, robsonsobral commented
FIXED.

2022-03-22 09:02 UTC, Alex-D requested changes
And, I think I can drop IE8 support now and use `classList`

Please remove `yarn.lock` since I now prefer package-lock.json :)

2022-03-22 12:54 UTC, robsonsobral commented
> I think I can drop IE8 support now and use `classList`

Are you sure? Move to v3 just because of that? No adding tests? I guess we could, at least, add code linting. Of course, keeping the simplicity and the small size.

2022-03-22 13:42 UTC, Alex-D commented
I will take some time to clean that with my eslint ruleset

IE8 is not supported in v2 since I already use classList and dataset, so what is wrong to keep them? I just need to update the README to remove IE8 from the list and go with IE10+ or did I miss something?

2022-03-22 14:07 UTC, robsonsobral commented
We could move to [ESBuild](https://esbuild.github.io/) as well.

2022-03-24 15:28 UTC, robsonsobral commented
The constant of the world is to change, @Alex-D .

https://github.com/WICG/display-locking/blob/main/explainers/hidden-content-explainer.md

2026-09-21 10:14 UTC, Alex-D commented
v3 now use `<template>`, solving this issue another way :)
Thank you for your PR and your time!

2026-09-21 10:14 UTC, closed without merging